export const x = [
	{
		createdAt: new Date(),
		createdBy: 'Puneet',
		title: 'First next app',
		subtitle: 'first',
		comments: 10,
		views: 100,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
	{
		createdAt: new Date(),
		createdBy: 'Harshit',
		title: 'Second next app',
		subtitle: 'second',
		comments: 20,
		views: 1000,
		activeUsers: 30,
		upVotes: 10,
		downVotes: 30,
	},
];
